### ISSUE TITLE
SpringRoll bower include...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/Bellhop#8]
What's the recommended way to include bellhop in a SpringRoll project now? It used bower originally, but with the update we're getting an error about `bellhop.js` not being found. Should I just lock in the earlier version of bellhop?

**Comment by probityrules** [comment]
Okay, so I don't know if this is the recommended fix, but I kept `bower.json` intact and updated `springroll.json` to use `components/bellhop/bellhop-umd.js` instead of `components/bellhop/dist/bellhop.js` and `components/bellhop/dist/bellhop.min.js`.

That said, this method does remove the readable version from debug builds; not sure whether that's important.

**Comment by chipbell4** [comment]
👋  @probityrules For some background (and others who find this later):

We refactored bellhop to be ES6 compliant and released a 2.0.0! However, the SpringRoll Template was pointing `bellhop` to `*` which was making it pick up the new release. I've since [patched the template to fix that](https://github.com/SpringRoll/SpringRollTemplate/pull/4).

However, the README has the name of the new file (which you've discovered is `bellhop-umd.js`). Or, you can just point bellhop to 1.2.0.

Sorry for the confusion!
